### PR TITLE
Intellicenter2/Firmware v1.064 Support

### PR DESCRIPTION
**Pull request by dustindclark**

### CODE REVIEW

**Comment by nickcurmi** [comment]
Thanks for updating to the new version and for all the great work you've done on this @dustindclark! I was stoked when I saw this existed a few weeks ago, because I've been trying to mess with the old pool controller plugin with no success. This worked great for me - very thankful you put it together. 

My pool guy actually updated my firmware on our panel earlier today, but I'm still on V1 of this plugin. I'm also on Node 12.19.0. 

Seems like the v1 of the plugin is still working with the updated IntelliCenter firmware. Do you recommend that I update the plugin with this latest update, or should I remain on v1 for now? If you do recommend updating the plugin, should I update node? I've been hesitant to update it because I'm not sure the effect it will have on my other plugins. 

What are your thoughts?

**Comment by dustindclark** [comment]
@nickcurmi the breaking changes are on startup, which is when your IntelliCenter circuits/heaters are discovered. If this breaks, the devices will still show in HomeKit but will become unresponsive...so it doesn't surprise me that it worked for a day. Chances are that either your homebridge instance restarted, or the IntellICenter socket connected/reconnected.

I'm not aware of any Node version dependencies in this plugin, but that definitely didn't change with the 2.x upgrade. Personally, I'm running on 16.10.x locally and 16.13.x on my Homebridge instance...so I can tell you for sure that those will work. If you run into issues on 12.x or 14.x, let me know, because that would be good to document.

**Comment by nickcurmi** [comment]
Thanks so much for the reply and the info @dustindclark! I installed the update to the plugin and all my accessories immediately started working again. They’ve been working for a few hours now with zero issues. I did not upgrade node, so it seems everything works well with node 12.x for now. 

Again, thank you so much for building this! Been wanting my pool connected to my home automation for 6 months now and am so excited to finally have it set up!

**Comment by nickcurmi** [comment]
@dustindclark I've got a weird one for you. This morning all of my accessories tied to the IntelliCenter plugin either said "No Response" or continuously stayed "Updating". I thought maybe there was something wrong with the plugin. However, when asking Siri to turn on my water feature, or controlled other accessories that fire the pool lights via HomeKit automation rules, both of them worked. I tested multiple times, and the scenes, Siri requests and automations worked every time. But I can't seem to control them via the accessory tiles in the home app because it thinks there is no response. 

Here are the latest home bridge logs:

[2/11/2022, 09:52:52] [homebridge-pentair-intellicenter] Setting Lights to false
[2/11/2022, 09:52:52] [homebridge-pentair-intellicenter] Setting Water Feature to false
[2/11/2022, 09:53:22] [homebridge-pentair-intellicenter] Setting Water Feature to true
[2/11/2022, 09:53:32] [homebridge-pentair-intellicenter] Setting Water Feature to false
[2/11/2022, 10:00:43] [homebridge-pentair-intellicenter] Setting Water Feature to true
[2/11/2022, 10:01:05] [homebridge-pentair-intellicenter] Setting Water Feature to false
[2/11/2022, 10:02:04] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:04] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:06] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:06] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:09] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:09] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:50] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:51] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:51] [homebridge-pentair-intellicenter] Setting Water Feature to true
[2/11/2022, 10:02:53] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:02:53] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:03:44] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:03:44] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:05:57] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:05:57] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:05:57] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:05:57] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:00] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:00] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:05] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:05] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 15 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:07] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27.77777777777778 exceeded maximum of 22.22222222222222. See https://git.io/JtMGR for more info.
[2/11/2022, 10:06:07] [homebridge-pentair-intellicenter] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 14.444444444444445 exceeded minimum of 21.11111111111111. See https://git.io/JtMGR for more info.

**Comment by nickcurmi** [comment]
Also, interestingly enough, the accessory tiles in the home bridge UI-X window still work just fine. It's just the tiles in the home app.

**Pull request merged**
